export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER_SUBJECTS = "GET_CURRENT_USER_SUBJECTS";
export const GET_CURRENT_SUBJECT = "GET_CURRENT_SUBJECT";
